### ISSUE TITLE
No filters and masks shows

### ISSUE THREAD

**Issue by tjasmin111** [DeepARSDK/android-deepar-amazon-ivs-sample-integration#2]
Thanks for the repo. The app runs and IVS works, but I don't know why no masks and filters are being shows. Maybe new Android Studio changed something that doesn't allow accessing those filters or .so files?! 
Would be great if you test it on the newest SDK and resolve the issues.

**Comment by DishoD** [comment]
@igor-aradski can you check this?

**Comment by igor-aradski** [comment]
@tjasmin111 versions of the SDK, IVS, and Android have been updated so can you check if the issue is still present? If so provide us with some additional info on logs and errors you receive.
